"""Logic-core — the generated-report provenance verifier (G5 graft, DF-009).

Adversarial corpus, not 'should work': present/absent × empty/non-empty ×
provenance-present/absent, exercised across BOTH formats this repo's extractor
stamps — the HTML-comment header on the `.md` artifacts AND the trailing
`"generated-by"` field inside `architecture-ir.json`. The JSON case is the whole
reason we deviate from the donor (which scanned only the first two lines): the
JSON stamps provenance last, so a head-2-only check would miss it."""
import json

import verify_generated as vgen

# The exact line 1 that tools/doc-synthesis/extract_architecture.py writes into
# dependency-graph.md / api-surface.md (see its _GENERATED_LINE).
MD_HEADER = ("<!-- generated by /friday:reference "
             "(tools/doc-synthesis/extract_architecture.py) — do not "
             "hand-edit; regenerated on commit -->")


def _ir_json(**extra) -> str:
    """architecture-ir.json shape: provenance stamped as a TRAILING field, the
    way write_outputs() emits it (dict(ir) then generated-by/generated-at)."""
    payload = {"modules": [], "edges": []}
    payload.update(extra)
    payload["generated-by"] = "/friday:reference (tools/doc-synthesis/extract_architecture.py)"
    payload["generated-at"] = "2026-07-13T00:00:00+00:00"
    return json.dumps(payload, indent=1)


# --- check_file unit: the core contract, one file at a time ---------------------

def test_present_nonempty_md_provenance_ok(tmp_path):
    f = tmp_path / "dependency-graph.md"
    f.write_text(MD_HEADER + "\n\n# Dependency graph (generated)\n", encoding="utf-8")
    entry = vgen.check_file(str(f), "reference", required=False)
    assert entry["ok"] and entry["present"] is True and entry["problem"] is None


def test_present_nonempty_json_provenance_ok(tmp_path):
    # Provenance lives at the END of the file, not in head-2 — this is the case
    # the donor's head-2-only scan could not have passed.
    f = tmp_path / "architecture-ir.json"
    f.write_text(_ir_json(), encoding="utf-8")
    entry = vgen.check_file(str(f), "reference", required=False)
    assert entry["ok"], entry


def test_empty_file_fails_EMPTY(tmp_path):
    f = tmp_path / "api-surface.md"
    f.write_text("", encoding="utf-8")
    entry = vgen.check_file(str(f), "reference", required=False)
    assert not entry["ok"] and entry["problem"] == "EMPTY"


def test_present_but_no_provenance_fails(tmp_path):
    f = tmp_path / "api-surface.md"
    f.write_text("# API surface\n\nreal content, but nobody stamped it.\n", encoding="utf-8")
    entry = vgen.check_file(str(f), "reference", required=False)
    assert not entry["ok"] and entry["problem"] == "MISSING PROVENANCE HEADER"


def test_wrong_cmd_provenance_fails(tmp_path):
    # A file stamped by /friday:reference must NOT satisfy a check for :handoff —
    # the cmd is load-bearing, not decorative.
    f = tmp_path / "dependency-graph.md"
    f.write_text(MD_HEADER + "\n\ncontent\n", encoding="utf-8")
    entry = vgen.check_file(str(f), "handoff", required=False)
    assert not entry["ok"] and entry["problem"] == "MISSING PROVENANCE HEADER"


def test_absent_optional_is_ok_pm_skipped(tmp_path):
    # Presence is optional: a file absent because the PM skipped this run is
    # expected, never a failure (the donor's documented posture).
    entry = vgen.check_file(str(tmp_path / "nope.md"), "reference", required=False)
    assert entry["ok"] and entry["present"] is False and entry["problem"] is None


def test_absent_required_fails(tmp_path):
    entry = vgen.check_file(str(tmp_path / "nope.md"), "reference", required=True)
    assert not entry["ok"] and entry["problem"] == "REQUIRED FILE ABSENT"


def test_json_compact_separator_still_matches(tmp_path):
    # Robustness: a re-serialization without the ': ' pretty separator must still
    # be recognized as provenance (we accept both separator styles).
    f = tmp_path / "architecture-ir.json"
    f.write_text('{"generated-by":"/friday:reference (x)","modules":[]}', encoding="utf-8")
    entry = vgen.check_file(str(f), "reference", required=False)
    assert entry["ok"], entry


# --- main()/CLI: exit codes 0 pass · 1 failure · 2 bad invocation ---------------

def test_main_all_pass_exit_0(tmp_path, capsys):
    f = tmp_path / "dependency-graph.md"
    f.write_text(MD_HEADER + "\n\n#\n", encoding="utf-8")
    rc = vgen.main(["--cmd", "reference", "--files", str(f), "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert out["ok"] and out["checked"] == 1 and out["cmd"] == "reference"


def test_main_empty_file_exit_1(tmp_path):
    f = tmp_path / "empty.md"
    f.write_text("", encoding="utf-8")
    assert vgen.main(["--cmd", "reference", "--files", str(f)]) == 1


def test_main_required_absent_exit_1(tmp_path):
    assert vgen.main(["--cmd", "reference", "--require", str(tmp_path / "missing.md")]) == 1


# Empty case (house rule: every grammar defines + tests its empty case). Zero
# targets is a bad invocation → exit 2, never a silent green.
def test_main_no_targets_exit_2():
    assert vgen.main(["--cmd", "reference"]) == 2


def test_main_bad_dir_exit_2(tmp_path):
    assert vgen.main(["--cmd", "reference", "--dir", str(tmp_path / "nope")]) == 2


def test_dir_scans_both_md_and_json(tmp_path, capsys):
    # --dir is adapted to this repo's generated set: it sweeps .md AND .json
    # (the donor only swept .md report dirs).
    gen = tmp_path / "generated"
    gen.mkdir()
    (gen / "dependency-graph.md").write_text(MD_HEADER + "\n\n#\n", encoding="utf-8")
    (gen / "api-surface.md").write_text(MD_HEADER + "\n\n#\n", encoding="utf-8")
    (gen / "architecture-ir.json").write_text(_ir_json(), encoding="utf-8")
    rc = vgen.main(["--cmd", "reference", "--dir", str(gen), "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert out["checked"] == 3


def test_dir_flags_a_headerless_generated_file(tmp_path):
    # A hand-edit that clobbers the header of a file already in the generated dir
    # is exactly what this catches on a re-run.
    gen = tmp_path / "generated"
    gen.mkdir()
    (gen / "dependency-graph.md").write_text("# oops, header gone\n", encoding="utf-8")
    assert vgen.main(["--cmd", "reference", "--dir", str(gen)]) == 1


def test_explicit_files_and_require_combine(tmp_path):
    good = tmp_path / "dependency-graph.md"
    good.write_text(MD_HEADER + "\n\n#\n", encoding="utf-8")
    # optional file present+good, required file absent → overall fail (exit 1).
    assert vgen.main(["--cmd", "reference",
                      "--files", str(good),
                      "--require", str(tmp_path / "must-exist.json")]) == 1
