"""Logic-core #3 — extractor IR emitter + the §6.7 diff classifier, incl. the
A.2 zero-module case and the TEST-10 seeded omission/hallucination drill."""
import json
import os

import extract_architecture as xa
import synthesis_diff as sd


def _seed_pkg(tmp_path):
    src = tmp_path / "app"
    src.mkdir()
    (src / "state.py").write_text(
        "import os\n"
        "from dataclasses import dataclass\n"
        "TOKEN = os.environ.get('APP_TOKEN')\n"
        "@dataclass\n"
        "class Job:\n"
        "    id: int\n"
        "    name: str\n", encoding="utf-8")
    (src / "web.py").write_text(
        "from fastapi import FastAPI\n"
        "import state\n"
        "app = FastAPI()\n"
        "@app.get('/jobs')\n"
        "def list_jobs():\n"
        "    return []\n"
        "@app.post('/jobs')\n"
        "def add_job():\n"
        "    import util\n"
        "    return util.ok()\n", encoding="utf-8")
    (src / "util.py").write_text("def ok():\n    return {'ok': True}\n", encoding="utf-8")
    return tmp_path


def test_ir_extraction(tmp_path):
    root = _seed_pkg(tmp_path)
    ir = xa.extract(str(root), src_dirs=["app"])
    ids = {m["id"] for m in ir["modules"]}
    assert ids == {"app.state", "app.web", "app.util"}
    edges = {(e["from"], e["to"], e["deferred"]) for e in ir["edges"]}
    assert ("app.web", "app.state", False) in edges
    assert ("app.web", "app.util", True) in edges          # function-local import flagged
    assert {(r["method"], r["path"]) for r in ir["routes"]} == {("GET", "/jobs"), ("POST", "/jobs")}
    assert any(c["name"] == "APP_TOKEN" for c in ir["config_surface"])
    assert any(d["name"] == "Job" and "id" in d["fields"] for d in ir["data_models"])
    assert ir.get("generated-empty") is not True
    assert ir["unparseable"] == []


def test_zero_module_empty_case(tmp_path):
    (tmp_path / "empty").mkdir()
    ir = xa.extract(str(tmp_path), src_dirs=["empty"])
    for key in ("modules", "edges", "routes", "config_surface", "data_models",
                "deploy_topology", "ambiguous_imports"):
        assert ir[key] == []
    assert ir["generated-empty"] is True
    # every downstream consumer accepts the zero-module input:
    dep_doc = xa.render_dependency_graph(ir)
    assert "0 modules" in dep_doc and dep_doc.count("```") % 2 == 0
    res = sd.diff(ir, "# Building blocks\n\n## Component inventory\n\n"
                      "_No components identified._\n")
    assert res["ok"], res


def test_write_outputs_are_provenance_stamped(tmp_path):
    root = _seed_pkg(tmp_path)
    out = xa.write_outputs(str(root), src_dirs=["app"])
    ir_path = os.path.join(str(root), "docs", "architecture", "generated",
                           "architecture-ir.json")
    assert os.path.isfile(ir_path)
    ir = json.load(open(ir_path, encoding="utf-8"))
    assert ir["modules"] and "generated-by" in ir
    dep = open(out["dependency_graph"], encoding="utf-8").read()
    assert "generated by /friday:reference" in dep.splitlines()[0].lower()


SYNTH_OK = """# Building blocks

## Component inventory

- `app.state` — state & models
- `app.web` — the API surface
- `app.util` — helpers

## Component diagram

```mermaid
graph LR
    app_state["app.state"]
    app_web["app.web"]
    app_util["app.util"]

    app_web --> app_state
    app_web -.->|deferred| app_util
```
"""


def test_diff_clean_synthesis_passes(tmp_path):
    ir = xa.extract(str(_seed_pkg(tmp_path)), src_dirs=["app"])
    res = sd.diff(ir, SYNTH_OK)
    assert res["ok"], res["findings"]


def test_diff_catches_seeded_omission_and_hallucination(tmp_path):
    """TEST-10: a deliberately-omitted node and a deliberately-hallucinated
    edge must both surface as findings — the diff IS the QA oracle."""
    ir = xa.extract(str(_seed_pkg(tmp_path)), src_dirs=["app"])
    omitted = SYNTH_OK.replace("- `app.util` — helpers\n", "")
    res1 = sd.diff(ir, omitted)
    assert not res1["ok"]
    assert any(f["kind"] == "omitted-module" and "app.util" in f["detail"]
               for f in res1["findings"])
    hallucinated = SYNTH_OK.replace("    app_web --> app_state",
                                    "    app_web --> app_state\n    app_state --> app_util")
    res2 = sd.diff(ir, hallucinated)
    assert not res2["ok"]
    assert any(f["kind"] == "hallucinated-edge" for f in res2["findings"])


def test_diff_flags_uncaptured_why(tmp_path):
    """§6.6 honesty story: a load-bearing structure with no DECISIONS entry is
    surfaced as an 'uncaptured why' gap, never silently ignored."""
    ir = xa.extract(str(_seed_pkg(tmp_path)), src_dirs=["app"])
    res = sd.diff(ir, SYNTH_OK, decisions_entries=[])
    assert any(f["kind"] == "uncaptured-why" for f in res["findings"])
    assert res["ok"]  # informational, not blocking — honesty, not a gate


# --- task #41: same-named modules make a bare import ambiguous — surfaced, never ------
# --- silently dropped, and the oracle stops punishing truth it cannot see -------------

def _seed_ambiguous(tmp_path):
    """Two subpackages each holding a server.py, one consumer bare-importing
    `server` — the INC-201 shape: the name resolved fine for eight increments,
    then a second same-named file appeared and the edge silently vanished."""
    for sub in ("pkga", "pkgb"):
        d = tmp_path / "svc" / sub
        d.mkdir(parents=True)
        (d / "server.py").write_text("X = 1\n", encoding="utf-8")
    (tmp_path / "svc" / "consumer.py").write_text("import server\n",
                                                  encoding="utf-8")
    return tmp_path


def test_ambiguous_bare_import_is_recorded_not_silently_dropped(tmp_path):
    """Live failure 2026-07-29: tests/test_server.py's `import server` lost its
    real edge the day tools/experiments/server.py was born, and the doc oracle
    then reported the doc's ACCURATE edge as hallucinated — following the
    'extractor is ground truth' rule deleted a true fact. Refusing to guess
    stays right (accuracy > recall); hiding that a guess was refused does not."""
    ir = xa.extract(str(_seed_ambiguous(tmp_path)), src_dirs=["svc"])
    # still no guessed edge — the refusal itself is unchanged
    assert all(e["from"] != "svc.consumer" for e in ir["edges"])
    (amb,) = ir["ambiguous_imports"]
    assert amb["from"] == "svc.consumer" and amb["name"] == "server"
    assert amb["candidates"] == ["svc.pkga.server", "svc.pkgb.server"]
    assert amb["line"] == 1


def test_unique_basename_still_resolves_with_no_ambiguity_noise(tmp_path):
    """The regression pin both ways: a unique basename keeps resolving to its
    edge, and a tree with nothing ambiguous reports an empty list — plain
    unresolvable symbols (stdlib, third-party) are NOT ambiguity."""
    ir = xa.extract(str(_seed_pkg(tmp_path)), src_dirs=["app"])
    assert ("app.web", "app.state") in {(e["from"], e["to"]) for e in ir["edges"]}
    assert ir["ambiguous_imports"] == []


SYNTH_AMBIG = """# Building blocks

## Component inventory

- `svc.consumer` — the bare importer
- `svc.pkga.server` — server A
- `svc.pkgb.server` — server B

## Component diagram

```mermaid
graph LR
    svc_consumer["svc.consumer"]
    svc_pkga_server["svc.pkga.server"]
    svc_pkgb_server["svc.pkgb.server"]

    svc_consumer --> svc_pkga_server
```
"""


def test_doc_edge_matching_a_recorded_ambiguity_is_not_hallucinated(tmp_path):
    """The oracle half: the extractor REFUSED to pick between two same-named
    candidates, so a doc edge naming one of them is knowledge the extractor
    lacks — an informational finding, never a blocking 'hallucination' that
    trains the synthesis to shed accurate content."""
    ir = xa.extract(str(_seed_ambiguous(tmp_path)), src_dirs=["svc"])
    res = sd.diff(ir, SYNTH_AMBIG)
    assert res["ok"], res["findings"]
    kinds = {f["kind"] for f in res["findings"]}
    assert "ambiguous-edge" in kinds and "hallucinated-edge" not in kinds


def test_a_doc_edge_outside_the_candidate_set_is_still_hallucinated(tmp_path):
    """The narrowness pin: only an edge the recorded ambiguity actually covers
    gets the benefit of the doubt — anything else stays a blocking finding."""
    ir = xa.extract(str(_seed_ambiguous(tmp_path)), src_dirs=["svc"])
    bad = SYNTH_AMBIG.replace("svc_consumer --> svc_pkga_server",
                              "svc_pkga_server --> svc_pkgb_server")
    res = sd.diff(ir, bad)
    assert not res["ok"]
    assert any(f["kind"] == "hallucinated-edge" for f in res["findings"])


# --- DF-017: import-form coverage --------------------------------------------
#
# The extractor missed `from pkg import a, b, c` when a/b/c are SUBMODULES of a
# package (package-root multi-import) — the exact form daemon.py/question_watcher
# use in the tether field build, silently dropping 11 real edges. These tests
# pin every import form the extractor must resolve, and (load-bearing) the rule
# that a package-root name is an edge iff it resolves to a real submodule
# (pkg/<name>.py or pkg/<name>/) and NOT when it is a plain symbol.

def _seed_import_forms(tmp_path):
    """A package `pkg` (with a subpackage `pkg.sub`) exercised by every import
    form. Each form targets a DISTINCT submodule so edges don't overlap and the
    per-form assertions stay independent; `helper` is a plain symbol defined in
    the package __init__ (importing it must NOT create an edge)."""
    src = tmp_path / "proj"
    src.mkdir()
    pkg = src / "pkg"
    pkg.mkdir()
    # __init__ defines a plain symbol — `from pkg import helper` is NOT an edge
    (pkg / "__init__.py").write_text("def helper():\n    return 1\n", encoding="utf-8")
    for name in ("a", "b", "c", "d", "e", "f", "g", "h", "i"):
        (pkg / f"{name}.py").write_text(f"VALUE = '{name}'\n", encoding="utf-8")
    subpkg = pkg / "sub"
    subpkg.mkdir()
    (subpkg / "__init__.py").write_text("", encoding="utf-8")
    (subpkg / "x.py").write_text("XV = 1\n", encoding="utf-8")
    (subpkg / "y.py").write_text("YV = 1\n", encoding="utf-8")
    # importer lives at the package root, so relative forms resolve against `pkg`
    (pkg / "consumer.py").write_text(
        "from __future__ import annotations\n"
        "from pkg import a, b, c\n"      # package-root MULTI submodule -> 3 edges (THE BUG)
        "from pkg import d as dd\n"      # package-root submodule via alias -> edge pkg.d
        "from pkg import helper\n"       # plain SYMBOL off the package root -> NO edge
        "import pkg.e\n"                 # dotted-absolute -> edge pkg.e
        "import pkg.f as ff\n"           # dotted-absolute + alias -> edge pkg.f
        "from pkg.g import VALUE\n"      # symbol from a named submodule -> edge pkg.g
        "from pkg.h import VALUE as v\n" # symbol-as-alias from a submodule -> edge pkg.h
        "from . import i\n"              # relative package-root single -> edge pkg.i
        "from .sub import x, y\n",       # relative subpackage MULTI submodule -> 2 edges
        encoding="utf-8")
    return src


def test_import_forms_all_resolved(tmp_path):
    """Every import form the extractor claims to handle produces exactly the
    intra-tree edges the code proves — and nothing it doesn't. `pkg` is the
    top-level package (root=proj, src=pkg), so the absolute `from pkg import …`
    names match the extractor's `pkg.*` module ids exactly as they would in a
    real tree run from the package root."""
    proj = _seed_import_forms(tmp_path)
    ir = xa.extract(str(proj), src_dirs=["pkg"])
    edges = {(e["from"], e["to"]) for e in ir["edges"]}
    C = "pkg.consumer"
    expected = {
        (C, "pkg.a"), (C, "pkg.b"), (C, "pkg.c"),  # package-root multi submodule
        (C, "pkg.d"),                              # package-root submodule via alias
        (C, "pkg.e"), (C, "pkg.f"),                # dotted import (+ alias)
        (C, "pkg.g"), (C, "pkg.h"),                # symbol (+ alias) from a submodule
        (C, "pkg.i"),                              # relative package-root single
        (C, "pkg.sub.x"), (C, "pkg.sub.y"),        # relative subpackage multi
    }
    assert expected <= edges, f"missing edges: {sorted(expected - edges)}"
    # the plain symbol off the package root must NOT resolve to any edge:
    assert (C, "pkg.helper") not in edges
    assert (C, "pkg.__init__") not in edges
    # nothing spurious out of the consumer:
    assert {t for f, t in edges if f == C} == {t for _, t in expected}


def test_field_shape_tether_package_root_imports(tmp_path):
    """Regression pinned to the DF-017 field evidence: the exact daemon.py and
    question_watcher.py package-root import blocks from the tether build. Before
    the fix the 8 daemon + 3 watcher submodule edges were silently dropped and
    five modules were falsely reported imported-by-0."""
    pkg = tmp_path / "tether"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    submods = ["audit_log", "file_transfer", "pause_state", "revival",
               "session_registry", "slack_ui", "snapshot", "tmux_driver",
               "auth_gate", "command_parser", "config", "question_detector",
               "question_watcher"]
    for m in submods:
        (pkg / f"{m}.py").write_text("X = 1\n", encoding="utf-8")
    # daemon's real import shape (multi-line package-root tuple + single forms)
    (pkg / "daemon.py").write_text(
        "from tether import (audit_log, file_transfer, pause_state, revival,\n"
        "                    session_registry, slack_ui, snapshot, tmux_driver)\n"
        "from tether.auth_gate import authorized\n"
        "from tether.command_parser import parse\n"
        "from tether.config import Config, load\n"
        "from tether.question_detector import detect\n"
        "from tether.question_watcher import QuestionWatcher\n",
        encoding="utf-8")
    (pkg / "question_watcher.py").write_text(
        "from tether import slack_ui, snapshot, tmux_driver\n"
        "from tether.question_detector import Form, detect\n",
        encoding="utf-8")

    ir = xa.extract(str(tmp_path), src_dirs=["tether"])
    edges = {(e["from"], e["to"]) for e in ir["edges"]}

    daemon_expected = {f"tether.{m}" for m in
                       ("audit_log", "file_transfer", "pause_state", "revival",
                        "session_registry", "slack_ui", "snapshot", "tmux_driver",
                        "auth_gate", "command_parser", "config",
                        "question_detector", "question_watcher")}
    daemon_got = {t for f, t in edges if f == "tether.daemon"}
    assert daemon_got == daemon_expected, f"daemon edges wrong: {daemon_got ^ daemon_expected}"

    watcher_got = {t for f, t in edges if f == "tether.question_watcher"}
    assert watcher_got == {"tether.slack_ui", "tether.snapshot",
                           "tether.tmux_driver", "tether.question_detector"}

    # the five modules the shipped graph falsely called imported-by-0:
    fan_in = {}
    for _, t in edges:
        fan_in[t] = fan_in.get(t, 0) + 1
    for m in ("slack_ui", "tmux_driver", "snapshot", "audit_log", "pause_state"):
        assert fan_in.get(f"tether.{m}", 0) >= 1, f"tether.{m} still imported-by-0"
