#!/usr/bin/env python3
"""Deterministic architecture extractor — the structure half of doc-synthesis.

Generalized from the proven iron-agent extractor (21 modules / 57 edges / full
route surface, 100% accurate, caught the LLM's omitted `config` node): walks a
Python tree with stdlib `ast` (pure static analysis — never imports the
target) and emits the language-agnostic IR pinned by TSOW Appendix A.1:

  modules[]        {id, path, loc}
  edges[]          {from, to, kind:"import", line, deferred}
  routes[]         {method, path, handler, module, line, protocol}
  config_surface[] {name, kind:"env", module, line}
  data_models[]    {name, kind:"dataclass", module, fields[], line}
  deploy_topology[]{kind, name, detail}
  unparseable[]    {module, error}          (fail loud per module, keep going)

Empty case (A.2, MUST-NAME): zero modules emits a well-formed document with
ALL arrays present and empty plus `"generated-empty": true` — never a missing
file, a null, or a crash — and every downstream consumer (the §6.7 diff, the
mermaid renderers) accepts it.

Rendered outputs (docs/architecture/generated/, provenance-stamped, always
regenerated — never hand-maintained): architecture-ir.json,
dependency-graph.md (mermaid graph LR + fan-in/out), api-surface.md.

The whole point: output cannot drift from code — re-run and it re-derives.
The LLM synthesizes rationale AROUND these facts; the diff between the two is
the QA oracle (tools/doc-synthesis/synthesis_diff.py).

Usage:
  python3 tools/doc-synthesis/extract_architecture.py --root . [--src app --src tools] [--check] [--json]

Pure stdlib.
"""
# Contract: docs/contracts/synthesis-handoff.md — this extractor is the producer of
# facts; cited on both sides of the handoff (A14).
from __future__ import annotations

import argparse
import ast
import json
import os
import sys
from datetime import datetime, timezone

_HTTP_METHODS = {"get", "post", "put", "delete", "patch", "head", "options", "trace"}
_ROUTE_ATTRS = _HTTP_METHODS | {"websocket", "route"}
_SKIP_DIRS = {".git", "__pycache__", "node_modules", ".friday", ".venv", "venv",
              "docs", ".pytest_cache", ".ruff_cache", "dist", "build"}

_GENERATED_LINE = ("<!-- generated by /friday:reference "
                   "(tools/doc-synthesis/extract_architecture.py) — do not "
                   "hand-edit; regenerated on commit -->")


# --- discovery -----------------------------------------------------------------

def _py_files(root: str, src_dirs: list[str] | None) -> list[str]:
    bases = [os.path.join(root, s) for s in (src_dirs or ["."])]
    out: list[str] = []
    for base in bases:
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
            for fn in sorted(filenames):
                if fn.endswith(".py"):
                    out.append(os.path.join(dirpath, fn))
    return sorted(set(out))


def _module_id(root: str, path: str) -> str:
    rel = os.path.relpath(path, root)
    return rel[:-3].replace(os.sep, ".").lstrip(".")


# --- import edges ------------------------------------------------------------------

def _edge_targets(node: ast.AST, importer: str, known: set[str],
                  by_basename: dict[str, list[str]]) -> list[tuple[str, int]]:
    """Intra-tree modules an import references. Resolves: package-relative
    (`from .x import y`), dotted-absolute matching a known id, and flat
    sys.path-style (`import friday_substrate`) via a UNIQUE basename match —
    ambiguous basenames are skipped rather than guessed (accuracy > recall).

    For `from PKG import a, b, c` the imported NAMES are candidate submodules:
    each name is an edge iff PKG/<name>.py or PKG/<name>/ exists in the tree
    (i.e. `PKG.<name>` is a known module) and is NOT an edge when it's a plain
    symbol off the package root (a function/class defined in PKG/__init__),
    which we cannot attribute to a module without importing. This is the
    package-root multi-import form (DF-017) — the shape daemon.py and
    question_watcher.py use; before, only `from PKG.sub import x` resolved and
    these submodule edges were silently dropped."""
    def resolve(name: str, line: int) -> tuple[str, int] | None:
        if name in known:
            return name, line
        head = name.split(".")[0]
        cands = by_basename.get(head, [])
        if len(cands) == 1:
            return cands[0], line
        return None

    targets: list[tuple[str, int]] = []

    def add(hit: tuple[str, int] | None) -> None:
        if hit is not None:
            targets.append(hit)

    if isinstance(node, ast.ImportFrom):
        line = node.lineno
        if node.level:  # relative: resolve against the importer's package
            pkg_parts = importer.split(".")[:-1]
            base = pkg_parts[: len(pkg_parts) - (node.level - 1)]
        else:
            base = []
        # dotted path of the package/module being imported FROM
        from_parts = [*base, *(node.module.split(".") if node.module else [])]
        # (a) module edge: `from PKG.mod import Sym` — the from-path IS a module
        if node.module:
            from_mod = ".".join(from_parts)
            add(resolve(from_mod, line)
                or (resolve(node.module, line) if node.level else None))
        # (b) submodule edge(s): each imported NAME that resolves to a real
        #     intra-tree submodule of the from-path (covers both `from PKG
        #     import a, b, c` and `from . import a, b`); plain symbols and
        #     star imports resolve to nothing and are skipped.
        for alias in node.names:
            if alias.name == "*":
                continue
            add(resolve(".".join([*from_parts, alias.name]), line))
    elif isinstance(node, ast.Import):
        for alias in node.names:
            add(resolve(alias.name, node.lineno))
    return targets


def _collect_edges(module: str, tree: ast.AST, known: set[str],
                   by_basename: dict[str, list[str]]) -> list[dict]:
    seen: set[tuple[str, str]] = set()
    edges: list[dict] = []

    def visit(node: ast.AST, deferred: bool) -> None:
        for child in ast.iter_child_nodes(node):
            inside_fn = deferred or isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef))
            if isinstance(child, (ast.Import, ast.ImportFrom)):
                for dst, line in _edge_targets(child, module, known, by_basename):
                    if dst == module or (module, dst) in seen:
                        continue
                    seen.add((module, dst))
                    edges.append({"from": module, "to": dst, "kind": "import",
                                  "line": line, "deferred": inside_fn})
            visit(child, inside_fn)

    visit(tree, False)
    return edges


# --- routes (FastAPI + Flask decorator shapes) ---------------------------------------

def _app_like_names(tree: ast.AST) -> set[str]:
    names = {"app", "router"}
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            fn = node.value.func
            callee = fn.id if isinstance(fn, ast.Name) else (
                fn.attr if isinstance(fn, ast.Attribute) else None)
            if callee in {"FastAPI", "APIRouter", "Flask", "Blueprint"}:
                for tgt in node.targets:
                    if isinstance(tgt, ast.Name):
                        names.add(tgt.id)
    return names


def _collect_routes(module: str, tree: ast.AST) -> list[dict]:
    app_names = _app_like_names(tree)
    routes: list[dict] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for dec in node.decorator_list:
            if not isinstance(dec, ast.Call):
                continue
            fn = dec.func
            if not (isinstance(fn, ast.Attribute) and isinstance(fn.value, ast.Name)
                    and fn.value.id in app_names and fn.attr in _ROUTE_ATTRS):
                continue
            if not (dec.args and isinstance(dec.args[0], ast.Constant)
                    and isinstance(dec.args[0].value, str)):
                continue
            path = dec.args[0].value
            if fn.attr == "route":  # Flask: methods kwarg, default GET
                methods = ["GET"]
                for kw in dec.keywords:
                    if kw.arg == "methods" and isinstance(kw.value, (ast.List, ast.Tuple)):
                        methods = [e.value for e in kw.value.elts
                                   if isinstance(e, ast.Constant) and isinstance(e.value, str)]
                for m in methods:
                    routes.append({"method": m.upper(), "path": path,
                                   "handler": node.name, "module": module,
                                   "line": node.lineno, "protocol": "http"})
            else:
                method = "WS" if fn.attr == "websocket" else fn.attr.upper()
                routes.append({"method": method, "path": path, "handler": node.name,
                               "module": module, "line": node.lineno,
                               "protocol": "ws" if method == "WS" else "http"})
    return routes


# --- config surface + data models ------------------------------------------------------

def _is_environ(node: ast.AST) -> bool:
    return ((isinstance(node, ast.Attribute) and node.attr == "environ")
            or (isinstance(node, ast.Name) and node.id == "environ"))


def _collect_config(module: str, tree: ast.AST) -> list[dict]:
    out, seen = [], set()
    for node in ast.walk(tree):
        name = None
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr == "get" and _is_environ(node.func.value)
                and node.args and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)):
            name = node.args[0].value
        elif (isinstance(node, ast.Subscript) and _is_environ(node.value)
              and isinstance(node.slice, ast.Constant)
              and isinstance(node.slice.value, str)):
            name = node.slice.value
        if name and (module, name) not in seen:
            seen.add((module, name))
            out.append({"name": name, "kind": "env", "module": module,
                        "line": node.lineno})
    return out


def _collect_models(module: str, tree: ast.AST) -> list[dict]:
    out = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        is_dc = any(
            (isinstance(d, ast.Name) and d.id == "dataclass")
            or (isinstance(d, ast.Attribute) and d.attr == "dataclass")
            or (isinstance(d, ast.Call) and (
                (isinstance(d.func, ast.Name) and d.func.id == "dataclass")
                or (isinstance(d.func, ast.Attribute) and d.func.attr == "dataclass")))
            for d in node.decorator_list)
        if not is_dc:
            continue
        fields = [s.target.id for s in node.body
                  if isinstance(s, ast.AnnAssign) and isinstance(s.target, ast.Name)]
        out.append({"name": node.name, "kind": "dataclass", "module": module,
                    "fields": fields, "line": node.lineno})
    return out


# --- deploy topology ---------------------------------------------------------------------

def _collect_deploy(root: str) -> list[dict]:
    out: list[dict] = []
    plugin_json = os.path.join(root, ".claude-plugin", "plugin.json")
    if os.path.isfile(plugin_json):
        try:
            with open(plugin_json, encoding="utf-8") as fh:
                data = json.load(fh)
            for name, cfg in (data.get("mcpServers") or {}).items():
                out.append({"kind": "mcp-server", "name": name,
                            "detail": " ".join([cfg.get("command", ""),
                                                *cfg.get("args", [])]).strip()})
        except (OSError, json.JSONDecodeError):
            pass
    hooks_json = os.path.join(root, "hooks", "hooks.json")
    if os.path.isfile(hooks_json):
        try:
            with open(hooks_json, encoding="utf-8") as fh:
                data = json.load(fh)
            for event, groups in (data.get("hooks") or {}).items():
                n = sum(len(g.get("hooks", [])) for g in groups)
                out.append({"kind": "hook-binding", "name": event,
                            "detail": f"{n} hook(s)"})
        except (OSError, json.JSONDecodeError):
            pass
    for fn in ("Dockerfile", "docker-compose.yml", "docker-compose.yaml"):
        if os.path.isfile(os.path.join(root, fn)):
            out.append({"kind": "container", "name": fn, "detail": "present"})
    wf_dir = os.path.join(root, ".github", "workflows")
    if os.path.isdir(wf_dir):
        for fn in sorted(os.listdir(wf_dir)):
            if fn.endswith((".yml", ".yaml")):
                out.append({"kind": "ci-workflow", "name": fn, "detail": "present"})
    return out


# --- driver -----------------------------------------------------------------------------

def extract(root: str, src_dirs: list[str] | None = None) -> dict:
    root = os.path.abspath(root)
    files = _py_files(root, src_dirs)
    known = {_module_id(root, p) for p in files}
    by_basename: dict[str, list[str]] = {}
    for mid in sorted(known):
        by_basename.setdefault(mid.split(".")[-1], []).append(mid)

    ir: dict = {"modules": [], "edges": [], "routes": [], "config_surface": [],
                "data_models": [], "deploy_topology": _collect_deploy(root),
                "unparseable": []}
    for path in files:
        mid = _module_id(root, path)
        try:
            with open(path, encoding="utf-8") as fh:
                source = fh.read()
            tree = ast.parse(source, filename=path)
        except (SyntaxError, OSError, UnicodeDecodeError) as exc:
            ir["unparseable"].append({"module": mid, "error": str(exc)})
            continue
        ir["modules"].append({"id": mid, "path": os.path.relpath(path, root),
                              "loc": source.count("\n") + 1})
        ir["edges"].extend(_collect_edges(mid, tree, known, by_basename))
        ir["routes"].extend(_collect_routes(mid, tree))
        ir["config_surface"].extend(_collect_config(mid, tree))
        ir["data_models"].extend(_collect_models(mid, tree))

    ir["edges"].sort(key=lambda e: (e["from"], e["to"]))
    ir["routes"].sort(key=lambda r: (r["path"], r["method"]))
    if not ir["modules"]:
        ir["deploy_topology"] = []
        ir["generated-empty"] = True
    return ir


# --- rendering -----------------------------------------------------------------------------

def _node_id(module: str) -> str:
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in module)
    return ("m_" + safe.strip("_")) if (not safe or not safe[0].isalpha()) else safe


def render_dependency_graph(ir: dict) -> str:
    mods = [m["id"] for m in ir["modules"]]
    lines = [_GENERATED_LINE, "", "# Dependency graph (generated)", "",
             f"Intra-tree import graph — **{len(mods)} modules, "
             f"{len(ir['edges'])} import edges**. Every edge is a literal "
             "`import` statement in the source; the C4 Component level, "
             "correct-by-construction.", "", "```mermaid", "graph LR"]
    for m in mods:
        lines.append(f'    {_node_id(m)}["{m}"]')
    lines.append("")
    for e in ir["edges"]:
        arrow = " -.->|deferred| " if e["deferred"] else " --> "
        lines.append(f"    {_node_id(e['from'])}{arrow}{_node_id(e['to'])}")
    lines += ["```", ""]

    fan_out = {m: 0 for m in mods}
    fan_in = {m: 0 for m in mods}
    for e in ir["edges"]:
        fan_out[e["from"]] += 1
        fan_in[e["to"]] += 1
    lines += ["## Fan-in / fan-out", "", "| Module | Imports (out) | Imported by (in) |",
              "| --- | ---: | ---: |"]
    for m in mods:
        lines.append(f"| `{m}` | {fan_out[m]} | {fan_in[m]} |")
    lines.append("")
    if ir["unparseable"]:
        lines += ["## Modules that failed to parse", ""]
        lines += [f"- `{u['module']}`: {u['error']}" for u in ir["unparseable"]]
        lines.append("")
    return "\n".join(lines) + "\n"


def render_api_surface(ir: dict) -> str:
    lines = [_GENERATED_LINE, "", "# API surface (generated)", "",
             f"**{len([r for r in ir['routes'] if r['method'] != 'WS'])} HTTP "
             f"routes, {len([r for r in ir['routes'] if r['method'] == 'WS'])} "
             "WebSocket** — extracted straight off the route decorators.", "",
             "| Method | Path | Handler | Source |", "| --- | --- | --- | --- |"]
    for r in ir["routes"]:
        lines.append(f"| {r['method']} | `{r['path']}` | `{r['handler']}` | "
                     f"`{r['module']}:{r['line']}` |")
    lines.append("")
    if ir["config_surface"]:
        lines += ["## Config surface (env)", ""]
        lines += [f"- `{c['name']}` — read in `{c['module']}:{c['line']}`"
                  for c in ir["config_surface"]]
        lines.append("")
    if ir["data_models"]:
        lines += ["## Data models", ""]
        lines += [f"- `{d['name']}` ({d['kind']}, `{d['module']}:{d['line']}`): "
                  + ", ".join(f"`{f}`" for f in d["fields"])
                  for d in ir["data_models"]]
        lines.append("")
    if ir["deploy_topology"]:
        lines += ["## Deploy topology", ""]
        lines += [f"- {t['kind']}: `{t['name']}` — {t['detail']}"
                  for t in ir["deploy_topology"]]
        lines.append("")
    return "\n".join(lines) + "\n"


def write_outputs(root: str, src_dirs: list[str] | None = None,
                  out_dir: str = os.path.join("docs", "architecture", "generated")) -> dict:
    ir = extract(root, src_dirs)
    stamped = dict(ir)
    stamped["generated-by"] = "/friday:reference (tools/doc-synthesis/extract_architecture.py)"
    stamped["generated-at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")

    out_abs = os.path.join(os.path.abspath(root), out_dir)
    os.makedirs(out_abs, exist_ok=True)
    paths = {"ir": os.path.join(out_abs, "architecture-ir.json"),
             "dependency_graph": os.path.join(out_abs, "dependency-graph.md"),
             "api_surface": os.path.join(out_abs, "api-surface.md")}
    with open(paths["ir"], "w", encoding="utf-8") as fh:
        json.dump(stamped, fh, indent=1)
    with open(paths["dependency_graph"], "w", encoding="utf-8") as fh:
        fh.write(render_dependency_graph(ir))
    with open(paths["api_surface"], "w", encoding="utf-8") as fh:
        fh.write(render_api_surface(ir))
    paths["summary"] = (f"{len(ir['modules'])} modules, {len(ir['edges'])} edges, "
                        f"{len(ir['routes'])} routes, "
                        f"{len(ir['unparseable'])} unparseable")
    return paths


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".")
    ap.add_argument("--src", action="append", default=None,
                    help="source subdir (repeatable; default: whole root)")
    ap.add_argument("--check", action="store_true", help="parse + validate only")
    ap.add_argument("--json", action="store_true", help="print the IR to stdout")
    args = ap.parse_args(argv)
    if not os.path.isdir(args.root):
        print(f"extract_architecture: no such dir: {args.root}", file=sys.stderr)
        return 2
    if args.check or args.json:
        ir = extract(args.root, args.src)
        dep, api = render_dependency_graph(ir), render_api_surface(ir)
        if dep.count("```") % 2 or api.count("```") % 2:
            print("error: unbalanced mermaid fences", file=sys.stderr)
            return 1
        print(json.dumps(ir, indent=1) if args.json else
              f"OK (check): {len(ir['modules'])} modules, {len(ir['edges'])} edges, "
              f"{len(ir['routes'])} routes, {len(ir['unparseable'])} unparseable")
        return 0
    out = write_outputs(args.root, args.src)
    for k in ("ir", "dependency_graph", "api_surface"):
        print(f"wrote {out[k]}")
    print(out["summary"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
