#!/usr/bin/env python3
"""friday generated-report provenance verifier (G5 graft, DF-009 delta).

The doc-synthesis pipeline emits provenance-stamped artifacts that are
"regenerated on every run, never hand-edited" (see reference.md Phase 1 and
tools/doc-synthesis/extract_architecture.py). This tool is the single
mechanical check on the core contract those artifacts must honor:

    present  →  non-empty  AND  carries the "generated by /friday:<cmd>" stamp

Presence is deliberately optional: a file absent because the PM skipped the
generating command this run is expected, never a failure (the doctrine's
"distinguish skipped from bugged"). Pass `--require <file>` for any file that
MUST exist this run (e.g. the outputs of a `/friday:reference` run, which
always regenerates them — zero modules still emits the well-formed empty
document, so the file is present and non-empty).

Two adaptations from the 1L donor, both forced by THIS repo's artifacts:
  1. Whole-file provenance scan, not head-2. `architecture-ir.json` stamps
     provenance as a TRAILING `"generated-by"` field (dict(ir) then the stamp),
     so a first-two-lines check would miss it. The `.md` artifacts still carry
     the stamp on line 1; a whole-file scan finds both.
  2. The stamp is matched in either form the extractor writes — the HTML-comment
     / prose form (`generated by /friday:<cmd>`, the .md files) or the JSON-field
     form (`"generated-by": "/friday:<cmd>`, architecture-ir.json), across both
     json.dump separator styles.

Command-specific extras (an archive move-manifest, a reconcile re-stamp
invariant) are NOT generalized here; they stay with their commands, exactly as
the donor left them.

Usage:
  python3 tools/verify_generated.py --cmd reference \\
      --files docs/architecture/generated/dependency-graph.md \\
              docs/architecture/generated/api-surface.md
  python3 tools/verify_generated.py --cmd reference \\
      --require docs/architecture/generated/architecture-ir.json
  python3 tools/verify_generated.py --cmd reference \\
      --dir docs/architecture/generated        # every .md and .json in the dir

Exit codes: 0 = every present (and every required) file passes; 1 = any
empty / stamp-less / required-but-absent file; 2 = bad invocation. Pure stdlib.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

# Extensions the extractor emits into a generated dir; --dir sweeps exactly these.
GENERATED_EXTS = (".md", ".json")


def provenance_signatures(cmd: str) -> tuple[str, ...]:
    """Every literal substring that counts as "stamped by /friday:<cmd>", one per
    format the extractor writes. A file carries provenance if it contains ANY of
    them. Pure — no I/O — so callers/tests can reason about it directly."""
    return (
        f"generated by /friday:{cmd}",       # HTML-comment / prose form (the .md artifacts)
        f'"generated-by": "/friday:{cmd}',   # JSON field, json.dump(indent=…) default ': ' separator
        f'"generated-by":"/friday:{cmd}',    # JSON field, compact ':' separator (re-serialized)
    )


def check_file(path: str, cmd: str, required: bool) -> dict:
    """One file against the core contract. Reads the file (not pure), returns a
    result dict with a stable shape: file/required/present/ok/problem."""
    entry = {"file": path, "required": required}
    if not os.path.isfile(path):
        entry.update(present=False, ok=not required,
                     problem=None if not required else "REQUIRED FILE ABSENT")
        return entry
    entry["present"] = True
    if os.path.getsize(path) == 0:
        entry.update(ok=False, problem="EMPTY")
        return entry
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError as exc:
        entry.update(ok=False, problem=f"UNREADABLE: {exc}")
        return entry
    if not any(sig in text for sig in provenance_signatures(cmd)):
        entry.update(ok=False, problem="MISSING PROVENANCE HEADER")
        return entry
    entry.update(ok=True, problem=None)
    return entry


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Verify generated artifacts: present → non-empty + provenance stamp.")
    ap.add_argument("--cmd", required=True,
                    help="the generating command name (stamp = 'generated by /friday:<cmd>')")
    ap.add_argument("--files", nargs="*", default=[], metavar="path",
                    help="files to check (absent = command skipped = OK)")
    ap.add_argument("--require", nargs="*", default=[], metavar="path",
                    help="files that MUST exist this run")
    ap.add_argument("--dir", default=None,
                    help="also check every .md/.json directly inside this directory")
    ap.add_argument("--json", action="store_true", dest="as_json")
    args = ap.parse_args(argv)

    targets: list[tuple[str, bool]] = [(f, False) for f in args.files]
    targets += [(f, True) for f in args.require]
    if args.dir:
        if not os.path.isdir(args.dir):
            print(f"verify_generated: --dir is not a directory: {args.dir}", file=sys.stderr)
            return 2
        listed = {t for t, _ in targets}
        targets += [(os.path.join(args.dir, fn), False)
                    for fn in sorted(os.listdir(args.dir))
                    if fn.endswith(GENERATED_EXTS)
                    and os.path.join(args.dir, fn) not in listed]
    if not targets:
        print("verify_generated: nothing to check — pass --files/--require/--dir",
              file=sys.stderr)
        return 2

    results = [check_file(path, args.cmd, required) for path, required in targets]
    failures = [r for r in results if not r["ok"]]
    out = {"ok": not failures, "cmd": args.cmd,
           "checked": len(results), "results": results}
    if args.as_json:
        print(json.dumps(out, indent=1))
    else:
        for r in failures:
            print(f"✗ {r['problem']}: {r['file']}")
        print(f"verify_generated: {'passed' if not failures else 'FAILED'} — "
              f"{len(results)} file(s) checked, {len(failures)} problem(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
